# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

    # isort
  - repo: https://github.com/PyCQA/isort
    rev: 5.10.1
    hooks:
      - id: isort

    # Black
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black

    # flake8
  - repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        args: ["--max-line-length=88", "--max-complexity=18", "--select=B,C,E,F,W,T4,B9", "--ignore=E203,E266,E501,W503,F403,F401,E402"]

    # Prospector
  - repo: https://github.com/PyCQA/prospector
    rev: 1.7.5 # The version of Prospector to use, if not 'master' for latest
    hooks:
      - id: prospector

  # MyPy
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        exclude: ^tests/
        args: [--strict]
